# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q7wbJpTd_q1NUpuCCnzDLnmZg9Cq4GAK
"""

# Commented out IPython magic to ensure Python compatibility.
#step 1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

#step 2
data=pd.read_csv("/content/indian_liver_patient.csv")

#step 3
data.head()

data.tail()

data.describe()

data.info()

data.isna()

data.columns

data.isnull

data["Albumin_and_Globulin_Ratio"].fillna(data["Albumin_and_Globulin_Ratio"].median(),inplace=True)

data.info()

#step 4
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

data["Gender"]=le.fit_transform(data.Gender)

data.describe()

#step 5
sns.countplot(x='Total_Protiens',data=data)

sns.countplot(x='Gender',data=data)

#step 6
#creating independent and dependent variable.

x=data[['Age','Total_Bilirubin','Direct_Bilirubin',	'Alkaline_Phosphotase',	'Alamine_Aminotransferase',
        'Aspartate_Aminotransferase',	'Total_Protiens',	'Albumin',	'Albumin_and_Globulin_Ratio',	'Dataset']]
y=data['Gender']

#step 7
#creating training and testing data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

#step 8
#model build

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()

model.fit(x_train,y_train)

model.score(x_test,y_test)

#step 9
#prediction
y_predict=model.predict(x_test)

#step 10
#metrics

from sklearn.metrics import classification_report
clf=classification_report(y_test,y_predict)
print(clf)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
print(cm)

# BAGGING

from sklearn.ensemble import BaggingClassifier

model1=BaggingClassifier()

model1.fit(x_train,y_train)

model1.score(x_test,y_test)

y_predict=model.predict(x_test)

from sklearn.metrics import classification_report
clf=classification_report(y_test,y_predict)
print(clf)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
print(cm)

# GradientBoosting

from sklearn.ensemble import GradientBoostingClassifier
model2=GradientBoostingClassifier()

model2.fit(x_train,y_train)

model2.score(x_test,y_test)

y_predict=model.predict(x_test)

from sklearn.metrics import classification_report
clf=classification_report(y_test,y_predict)
print(clf)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
print(cm)



